In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('mountains.csv')
df

Age      Gender  Income Education_Level  Travel_Frequency  \
0       56        male   71477        bachelor                 9   
1       69        male   88740          master                 1   
2       46      female   46562          master                 0   
3       32  non-binary   99044     high school                 6   
4       60      female  106583     high school                 5   
...    ...         ...     ...             ...               ...   
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0                   skiing             2477     urban                     175   
1                 swimming             4777  suburban                     228   
2                   skiing             1469     urban                      71   
3                   hiking             1482     rural                      31   
4               sunbathing              516  suburban                      23   
...                    ...              ...       ...                     ...   
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                       267          summer     0                       1   
1                       190            fall     0                       1   
2                       280          winter     0                       0   
3                       255          summer     1                       0   
4                       151          winter     1                       1   
...                     ...             ...   ...                     ...   
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
0               1  
1               0  
2               1  
3               1  
4               0  
...           ...  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0  

[52444 rows x 14 columns]

In [3]:
df.shape

(52444, 14)

In [4]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education_Level', 'Travel_Frequency',
       'Preferred_Activities', 'Vacation_Budget', 'Location',
       'Proximity_to_Mountains', 'Proximity_to_Beaches', 'Favorite_Season',
       'Pets', 'Environmental_Concerns', 'Preference'],
      dtype='object')

In [5]:
df.dtypes

Age                        int64
Gender                    object
Income                     int64
Education_Level           object
Travel_Frequency           int64
Preferred_Activities      object
Vacation_Budget            int64
Location                  object
Proximity_to_Mountains     int64
Proximity_to_Beaches       int64
Favorite_Season           object
Pets                       int64
Environmental_Concerns     int64
Preference                 int64
dtype: object

In [6]:
df['Gender'].value_counts()

Gender
female        17638
male          17522
non-binary    17284
Name: count, dtype: int64

In [7]:
df['Education_Level'].value_counts()

Education_Level
doctorate      13293
bachelor       13127
high school    13072
master         12952
Name: count, dtype: int64

In [8]:
df['Preferred_Activities'].value_counts()

Preferred_Activities
sunbathing    13221
skiing        13167
hiking        13102
swimming      12954
Name: count, dtype: int64

In [9]:
df['Location'].value_counts()

Location
suburban    17503
urban       17476
rural       17465
Name: count, dtype: int64

In [10]:
df['Favorite_Season'].value_counts()

Favorite_Season
summer    13303
fall      13170
winter    13019
spring    12952
Name: count, dtype: int64

In [11]:
df['Preference'].value_counts()

Preference
0    39296
1    13148
Name: count, dtype: int64

In [12]:
df.head()

Age      Gender  Income Education_Level  Travel_Frequency  \
0   56        male   71477        bachelor                 9   
1   69        male   88740          master                 1   
2   46      female   46562          master                 0   
3   32  non-binary   99044     high school                 6   
4   60      female  106583     high school                 5   

  Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0               skiing             2477     urban                     175   
1             swimming             4777  suburban                     228   
2               skiing             1469     urban                      71   
3               hiking             1482     rural                      31   
4           sunbathing              516  suburban                      23   

   Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                   267          summer     0                       1   
1                   190            fall     0                       1   
2                   280          winter     0                       0   
3                   255          summer     1                       0   
4                   151          winter     1                       1   

   Preference  
0           1  
1           0  
2           1  
3           1  
4           0

In [13]:
df.tail()

Age      Gender  Income Education_Level  Travel_Frequency  \
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0

In [14]:
df.isna().sum()

Age                       0
Gender                    0
Income                    0
Education_Level           0
Travel_Frequency          0
Preferred_Activities      0
Vacation_Budget           0
Location                  0
Proximity_to_Mountains    0
Proximity_to_Beaches      0
Favorite_Season           0
Pets                      0
Environmental_Concerns    0
Preference                0
dtype: int64

In [15]:
X = df.drop(columns=["Preference"])  # Replace 'target' with your actual column name
Y = df["Preference"]

In [17]:
from imblearn.over_sampling import RandomOverSampler


oversampler = RandomOverSampler(random_state=42)


X_resampled, Y_resampled = oversampler.fit_resample(X, Y)

In [ ]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender']=lab.fit_transform(df['Gender'])
df['Education_Level']=lab.fit_transform(df['Education_Level'])
df['Preferred_Activities']=lab.fit_transform(df['Preferred_Activities'])
df['Location']=lab.fit_transform(df['Location'])
df['Favorite_Season']=lab.fit_transform(df['Favorite_Season'])
df

Age  Gender  Income  Education_Level  Travel_Frequency  \
0       56       1   71477                0                 9   
1       69       1   88740                3                 1   
2       46       0   46562                3                 0   
3       32       2   99044                2                 6   
4       60       0  106583                2                 5   
...    ...     ...     ...              ...               ...   
52439   67       0   85325                3                 3   
52440   37       0  110346                0                 7   
52441   53       2   71080                1                 7   
52442   40       0   75174                1                 9   
52443   33       2   34475                3                 6   

       Preferred_Activities  Vacation_Budget  Location  \
0                         1             2477         2   
1                         3             4777         1   
2                         1             1469         2   
3                         0             1482         0   
4                         2              516         1   
...                     ...              ...       ...   
52439                     0             1762         1   
52440                     3             1676         2   
52441                     3             3877         2   
52442                     3             4620         1   
52443                     0              928         1   

       Proximity_to_Mountains  Proximity_to_Beaches  Favorite_Season  Pets  \
0                         175                   267                2     0   
1                         228                   190                0     0   
2                          71                   280                3     0   
3                          31                   255                2     1   
4                          23                   151                3     1   
...                       ...                   ...              ...   ...   
52439                      51                   262                0     1   
52440                     259                    84                1     1   
52441                     164                    27                0     0   
52442                     173                    10                2     0   
52443                     218                   166                1     1   

       Environmental_Concerns  Preference  
0                           1           1  
1                           1           0  
2                           0           1  
3                           0           1  
4                           1           0  
...                       ...         ...  
52439                       0           1  
52440                       0           0  
52441                       1           0  
52442                       1           0  
52443                       0           0  

[52444 rows x 14 columns]

In [ ]:
x=df.iloc[:,:-1].values
x

array([[   56,     1, 71477, ...,     2,     0,     1],
       [   69,     1, 88740, ...,     0,     0,     1],
       [   46,     0, 46562, ...,     3,     0,     0],
       ...,
       [   53,     2, 71080, ...,     0,     0,     1],
       [   40,     0, 75174, ...,     2,     0,     1],
       [   33,     2, 34475, ...,     1,     1,     0]], shape=(52444, 13))

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, ..., 0, 0, 0], shape=(52444,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[    49,      0,  69367, ...,      1,      0,      0],
       [    50,      2, 103956, ...,      3,      1,      1],
       [    30,      1,  91462, ...,      2,      1,      1],
       ...,
       [    63,      0,  68714, ...,      1,      0,      1],
       [    20,      2,  30887, ...,      3,      1,      0],
       [    38,      2,  78821, ...,      2,      0,      1]],
      shape=(36710, 13))

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
from sklearn.naive_bayes import BernoulliNB
nav=BernoulliNB()
from sklearn.svm import SVC
sup=SVC()
from sklearn.metrics import confusion_matrix,classification_report
lst=[knn,nav,sup]

In [ ]:
for i in lst:
    print("Model Name is******^^^^^^^^^******:",i)
    i.fit(x_train,y_train)
    y_pred=i.predict(x_test)
    print("Performance Evaluation Method********^^^^^^^******:",i)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

Model Name is******^^^^^^^^^******: KNeighborsClassifier(n_neighbors=7)
Performance Evaluation Method********^^^^^^^******: KNeighborsClassifier(n_neighbors=7)
[[11457   391]
 [  719  3167]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95     11848
           1       0.89      0.81      0.85      3886

    accuracy                           0.93     15734
   macro avg       0.92      0.89      0.90     15734
weighted avg       0.93      0.93      0.93     15734

Model Name is******^^^^^^^^^******: BernoulliNB()
Performance Evaluation Method********^^^^^^^******: BernoulliNB()
[[11848     0]
 [ 1919  1967]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.93     11848
           1       1.00      0.51      0.67      3886

    accuracy                           0.88     15734
   macro avg       0.93      0.75      0.80     15734
weighted avg       0.90      0.88      0.86     15734

Model Na